# Generated by Django 5.1.9 on 2026-09-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=64)),
                ('completed_at', models.DateTimeField()),
                ('total_fetched', models.PositiveIntegerField()),
                ('total_cleaned', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('youtube_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('youtube_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('fetched_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('percentage', models.FloatField()),
                ('avg_likes', models.FloatField()),
                ('impact_score', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='api.analysis')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=200)),
                ('cleaning_version', models.CharField(max_length=40)),
                ('cleaned_text', models.TextField()),
                ('vector', models.JSONField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('display_text', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.cluster')),
                ('embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.embedding')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.video'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.video'),
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('analysis', 'rank'), name='unique_cluster_rank'),
        ),
        migrations.AddConstraint(
            model_name='embedding',
            constraint=models.UniqueConstraint(fields=('comment', 'text_hash', 'model_version', 'cleaning_version'), name='unique_comment_embedding'),
        ),
        migrations.AddConstraint(
            model_name='clustermembership',
            constraint=models.UniqueConstraint(fields=('cluster', 'embedding'), name='unique_cluster_member'),
        ),
    ]
